[phases.setup]
nixPkgs = ["openjdk17", "maven"]

[phases.install]
cmds = ["cd backend && mvn clean package -DskipTests"]

[start]
cmd = "cd backend && java -jar target/delicias-da-katie-0.0.1-SNAPSHOT.jar" 