[build]
builder = "nixpacks"

[deploy]
startCommand = "java -jar target/delicias-da-katie-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[build.environment]
JAVA_VERSION = "21"
MAVEN_VERSION = "3.9.5" 